assignment/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from main import views as main_views

urlpatterns = [
    # Examples:
    # url(r'^$', 'assignment.views.home', name='home'),
    # url(r'^blog/', include('blog.urls')),

    url(r'^admin/', include(admin.site.urls)),
    url(r'^manager/cleaners/', include('cleaners.urls', namespace='cleaners')),
    url(r'^manager/customers/', include('customers.urls', namespace='customers')),
    url(r'^manager/cities/', include('cities.urls', namespace='cities')),
    url(r'^manager/bookings/', include('bookings.urls', namespace='bookings')),
    url(r'^manager/', main_views.home_manager),
    url(r'^$', main_views.home)
]

cities/urls.py
from django.conf.urls import url

from .views import (
    CityList,
    CityDetail,
    CityCreation,
    CityUpdate,
    CityDelete
)

urlpatterns = [

    url(r'^$', CityList.as_view(), name='list'),
    url(r'^(?P<pk>\d+)$', CityDetail.as_view(), name='detail'),
    url(r'^new$', CityCreation.as_view(), name='new'),
    url(r'^edit/(?P<pk>\d+)$', CityUpdate.as_view(), name='edit'),
    url(r'^delete/(?P<pk>\d+)$', CityDelete.as_view(), name='delete'),

]

cities/models.py
from django.db import models


class City(models.Model):
    # The name of the city also acts as an unique identifier
    # If need be, we can add state/county/district here
	name = models.CharField(max_length=200, unique=True)

	def __unicode__(self):
		return str(self.name)

cities/views.py
from django.core.urlresolvers import reverse_lazy

from django.views.generic import ListView
from django.views.generic.detail import DetailView
from django.views.generic.edit import (
    CreateView,
    UpdateView,
    DeleteView
)

from .models import City


class CityList(ListView):
    model = City


class CityDetail(DetailView):
    model = City


class CityCreation(CreateView):
    model = City
    success_url = reverse_lazy('cities:list')
    fields = ['name']


class CityUpdate(UpdateView):
    model = City
    success_url = reverse_lazy('cities:list')
    fields = ['name']


class CityDelete(DeleteView):
    model = City
    success_url = reverse_lazy('cities:list')

cities/templates/cities/city_confirm_delete.html
{% extends "base_manager.html" %}


{% block content %}
    <form method="post">{% csrf_token %}
        Are you sure you want to delete "{{ object }}"?
        <input type="submit" value="Submit" />
    </form>
{% endblock content %}

cities/templates/cities/city_detail.html
{% extends "base_manager.html" %}


{% block content %}
    <h1>{{ city.name }}</h1>
    <p>
        <a href="{% url "cities:list" %}">Back</a>
    </p>
{% endblock content %}

cities/templates/cities/city_form.html
{% extends "base_manager.html" %}


{% block content %}
    <form method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <input type="submit" value="Submit" />
    </form>
{% endblock content %}

cities/templates/cities/city_list.html
{% extends "base_manager.html" %}


{% block content %}
    <h1>Cities</h1>

    <p>
        <a href="{% url "cities:new" %}">Add a city</a>
    </p>
    <table class="table">
        <thead>
          <tr>
                <th>Name</th>
                <th></th>
          </tr>
        </thead>
        <tbody>
            {% for city in object_list %}
                <tr>
                    <td>{{ city.name }}</td>
                    <td>
                        <a href="{% url "cities:detail" city.id %}">Show</a> |
                        <a href="{% url "cities:edit" city.id %}">Edit</a> |
                        <a href="{% url "cities:delete" city.id %}">Delete</a>
                    </td>
                </tr>
            {% endfor %}
        </tbody>
    </table>
{% endblock content %}