assignment/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from main import views as main_views

urlpatterns = [
    # Examples:
    # url(r'^$', 'assignment.views.home', name='home'),
    # url(r'^blog/', include('blog.urls')),

    url(r'^admin/', include(admin.site.urls)),
    url(r'^manager/cleaners/', include('cleaners.urls', namespace='cleaners')),
    url(r'^manager/customers/', include('customers.urls', namespace='customers')),
    url(r'^manager/cities/', include('cities.urls', namespace='cities')),
    url(r'^manager/bookings/', include('bookings.urls', namespace='bookings')),
    url(r'^manager/', main_views.home_manager),
    url(r'^$', main_views.home)
]

cities/urls.py
from django.conf.urls import url

from .views import (
    CityList,
    CityDetail,
    CityCreation,
    CityUpdate,
    CityDelete
)

urlpatterns = [

    url(r'^$', CityList.as_view(), name='list'),
    url(r'^(?P<pk>\d+)$', CityDetail.as_view(), name='detail'),
    url(r'^new$', CityCreation.as_view(), name='new'),
    url(r'^edit/(?P<pk>\d+)$', CityUpdate.as_view(), name='edit'),
    url(r'^delete/(?P<pk>\d+)$', CityDelete.as_view(), name='delete'),

]

customers/urls.py
from django.conf.urls import url

from .views import (
    CustomerList,
    CustomerDetail,
    CustomerCreation,
    CustomerUpdate,
    CustomerDelete
)

urlpatterns = [

    url(r'^$', CustomerList.as_view(), name='list'),
    url(r'^(?P<pk>\d+)$', CustomerDetail.as_view(), name='detail'),
    url(r'^new$', CustomerCreation.as_view(), name='new'),
    url(r'^edit/(?P<pk>\d+)$', CustomerUpdate.as_view(), name='edit'),
    url(r'^delete/(?P<pk>\d+)$', CustomerDelete.as_view(), name='delete'),

]

customers/models.py
from django.db import models

class Customer(models.Model):
    # By default, charfields are required
    first_name = models.CharField(max_length=100)
    last_name = models.CharField(max_length=100)
    # Phone number is required because it will be used as identification for users
    # We don't make it unique because it will fail validations
    phone_number = models.CharField(max_length=50)

customers/views.py
from django.core.urlresolvers import reverse_lazy

from django.views.generic import ListView
from django.views.generic.detail import DetailView
from django.views.generic.edit import (
    CreateView,
    UpdateView,
    DeleteView
)

from .models import Customer


class CustomerList(ListView):
    model = Customer


class CustomerDetail(DetailView):
    model = Customer


class CustomerCreation(CreateView):
    model = Customer
    success_url = reverse_lazy('customers:list')
    fields = ['first_name', 'last_name', 'phone_number']


class CustomerUpdate(UpdateView):
    model = Customer
    success_url = reverse_lazy('customers:list')
    fields = ['first_name', 'last_name', 'phone_number']


class CustomerDelete(DeleteView):
    model = Customer
    success_url = reverse_lazy('customers:list')

customers/templates/customers/customer_confirm_delete.html
{% extends "base_manager.html" %}


{% block content %}
    <form method="post">{% csrf_token %}
        ¿Are you sure you want to delete "{{ object }}"?
        <input type="submit" value="Submit" />
    </form>
{% endblock content %}

customers/templates/customers/customer_detail.html
{% extends "base_manager.html" %}


{% block content %}
    <h1>{{ customer.first_name }}</h1>
    <p>Score: <i>{{ customer.quality_score }}</i></p>
    <p>
        <a href="{% url "customers:list" %}">Back</a>
    </p>
{% endblock content %}

customers/templates/customers/customer_form.html
{% extends "base_manager.html" %}


{% block content %}
    <form method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <input type="submit" value="Submit" />
    </form>
{% endblock content %}

customers/templates/customers/customer_list.html
{% extends "base_manager.html" %}


{% block content %}
    <h1>Customers</h1>

    <p>
        <a href="{% url "customers:new" %}">Add a customer</a>
    </p>
    <table class="table">
        <thead>
          <tr>
                <th>Name</th>
                <th></th>
          </tr>
        </thead>
        <tbody>
            {% for customer in object_list %}
                <tr>
                    <td>{{ customer.first_name }}</td>
                    <td>
                        <a href="{% url "customers:detail" customer.id %}">Show</a> |
                        <a href="{% url "customers:edit" customer.id %}">Edit</a> |
                        <a href="{% url "customers:delete" customer.id %}">Delete</a>
                    </td>
                </tr>
            {% endfor %}
        </tbody>
    </table>
{% endblock content %}