assignment/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from main import views as main_views

urlpatterns = [
    # Examples:
    # url(r'^$', 'assignment.views.home', name='home'),
    # url(r'^blog/', include('blog.urls')),

    url(r'^admin/', include(admin.site.urls)),
    url(r'^manager/cleaners/', include('cleaners.urls', namespace='cleaners')),
    url(r'^manager/customers/', include('customers.urls', namespace='customers')),
    url(r'^manager/cities/', include('cities.urls', namespace='cities')),
    url(r'^manager/bookings/', include('bookings.urls', namespace='bookings')),
    url(r'^manager/', main_views.home_manager),
    url(r'^$', main_views.home)
]

cities/urls.py
from django.conf.urls import url

from .views import (
    CityList,
    CityDetail,
    CityCreation,
    CityUpdate,
    CityDelete
)

urlpatterns = [

    url(r'^$', CityList.as_view(), name='list'),
    url(r'^(?P<pk>\d+)$', CityDetail.as_view(), name='detail'),
    url(r'^new$', CityCreation.as_view(), name='new'),
    url(r'^edit/(?P<pk>\d+)$', CityUpdate.as_view(), name='edit'),
    url(r'^delete/(?P<pk>\d+)$', CityDelete.as_view(), name='delete'),

]

cleaners/urls.py
from django.conf.urls import url

from .views import (
    CleanerList,
    CleanerDetail,
    CleanerCreation,
    CleanerUpdate,
    CleanerDelete
)

urlpatterns = [

    url(r'^$', CleanerList.as_view(), name='list'),
    url(r'^(?P<pk>\d+)$', CleanerDetail.as_view(), name='detail'),
    url(r'^new$', CleanerCreation.as_view(), name='new'),
    url(r'^edit/(?P<pk>\d+)$', CleanerUpdate.as_view(), name='edit'),
    url(r'^delete/(?P<pk>\d+)$', CleanerDelete.as_view(), name='delete'),

]

cleaners/models.py
from django.db import models
from django.core.validators import MinValueValidator, MaxValueValidator

from cities.models import City

class Cleaner(models.Model):
    # By default, charfields are required
    first_name = models.CharField(max_length=100)
    last_name = models.CharField(max_length=100)
    # Required, must be a number between 0.0 and 5.0
    quality_score = models.DecimalField(max_digits=2, decimal_places=1, \
    	validators=[MinValueValidator(0.0), MaxValueValidator(5.0)])

    # The cities in which a cleaner works
    # If more information is needed per city (e.g. quality score or schedule), `through` can be used
    cities = models.ManyToManyField(City, related_name='cleaners')

    def __unicode__(self):
    	return '%s, %s' %(self.last_name, self.first_name)
    

cleaners/forms.py
from django import forms

from .models import Cleaner
from cities.models import City

class CleanerForm(forms.ModelForm):
    cities = forms.ModelMultipleChoiceField(
        queryset=City.objects.all(),
        widget=forms.CheckboxSelectMultiple
    )

    class Meta:
        model = Cleaner
        fields = ['first_name', 'last_name', 'quality_score', 'cities']

cleaners/views.py
from django.core.urlresolvers import reverse_lazy

from django.views.generic import ListView
from django.views.generic.detail import DetailView
from django.views.generic.edit import (
    CreateView,
    UpdateView,
    DeleteView
)

from .models import Cleaner
from .forms import CleanerForm


class CleanerList(ListView):
    model = Cleaner


class CleanerDetail(DetailView):
    model = Cleaner


class CleanerCreation(CreateView):
    form_class = CleanerForm
    template_name = 'cleaners/cleaner_form.html'
    success_url = reverse_lazy('cleaners:list')


class CleanerUpdate(UpdateView):
    form_class = CleanerForm
    template_name = 'cleaners/cleaner_form.html'
    success_url = reverse_lazy('cleaners:list')
    queryset = Cleaner.objects.all()


class CleanerDelete(DeleteView):
    model = Cleaner
    success_url = reverse_lazy('cleaners:list')

cleaners/templates/cleaners/cleaner_confirm_delete.html
{% extends "base_manager.html" %}


{% block content %}
    <form method="post">{% csrf_token %}
        ¿Are you sure you want to delete "{{ object }}"?
        <input type="submit" value="Submit" />
    </form>
{% endblock content %}

cleaners/templates/cleaners/cleaner_detail.html
{% extends "base_manager.html" %}


{% block content %}
    <h1>{{ cleaner.first_name }}</h1>
    <p>Score: <i>{{ cleaner.quality_score }}</i></p>
    <p>
        <a href="{% url "cleaners:list" %}">Back</a>
    </p>
{% endblock content %}

cleaners/templates/cleaners/cleaner_form.html
{% extends "base_manager.html" %}


{% block content %}
    <form method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <input type="submit" value="Submit" />
    </form>
{% endblock content %}

cleaners/templates/cleaners/cleaner_list.html
{% extends "base_manager.html" %}


{% block content %}
    <h1>Cleaners</h1>

    <p>
        <a href="{% url "cleaners:new" %}">Add a cleaner</a>
    </p>
    <table class="table">
        <thead>
          <tr>
                <th>Name</th>
                <th></th>
          </tr>
        </thead>
        <tbody>
            {% for cleaner in object_list %}
                <tr>
                    <td>{{ cleaner.first_name }}</td>
                    <td>
                        <a href="{% url "cleaners:detail" cleaner.id %}">Show</a> |
                        <a href="{% url "cleaners:edit" cleaner.id %}">Edit</a> |
                        <a href="{% url "cleaners:delete" cleaner.id %}">Delete</a>
                    </td>
                </tr>
            {% endfor %}
        </tbody>
    </table>
{% endblock content %}